# Generated by Django 3.2.5 on 2021-08-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reuniones_comunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
                ('dia', models.CharField(max_length=15)),
                ('horario', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='reuniones_especiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
                ('dia', models.CharField(max_length=15)),
                ('horario', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=64)),
            ],
        ),
    ]
