# Generated by Django 3.2.5 on 2021-08-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_ppal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniones_comunes',
            name='dia',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='reuniones_comunes',
            name='horario',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='reuniones_especiales',
            name='dia',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='reuniones_especiales',
            name='horario',
            field=models.CharField(max_length=64),
        ),
    ]
